import { writeFileSync } from "node:fs";
import type { CacheEntry } from "./cache";

export function emitDts(outPath: string, entries: CacheEntry[]): void {
  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by bun-sqlx. Do not edit.");
  lines.push("// Run `bun-sqlx prepare` to regenerate.");
  lines.push("");
  lines.push('declare module "bun-sqlx" {');
  lines.push("  interface KnownQueries {");

  const seen = new Set<string>();
  for (const e of entries.slice().sort((a, b) => a.query.localeCompare(b.query))) {
    if (seen.has(e.query)) continue;
    seen.add(e.query);
    const key = JSON.stringify(e.query);
    const paramsTs = e.paramTsTypes.length === 0 ? "[]" : `[${e.paramTsTypes.join(", ")}]`;
    let rowTs: string;
    if (!e.hasResultSet) {
      rowTs = "never";
    } else {
      const cols = e.columns.map((c) => {
        const nullable = c.forceNonNull ? false : c.forceNullable ? true : c.nullable;
        const t = nullable ? `${c.tsType} | null` : c.tsType;
        return `${JSON.stringify(c.name)}: ${t}`;
      });
      rowTs = `{ ${cols.join("; ")} }`;
    }
    lines.push(`    ${key}: { params: ${paramsTs}; row: ${rowTs} };`);
  }

  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  writeFileSync(outPath, lines.join("\n") + "\n");
}
